Repository NOW-SOPT-APP4-KREAM/KREAM-Server, pull requests merged in 2024-05, with the labels that each got.

#2 [chore] #1 - 기본 프로젝트 세팅
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/app/kream/KreamApplication.java
  src/main/java/com/app/kream/common/CommonResponse.java
  src/main/java/com/app/kream/common/GlobalExceptionHandler.java
  src/main/java/com/app/kream/config/JpaAuditingConfig.java
  src/main/java/com/app/kream/config/SwaggerConfig.java
  src/main/java/com/app/kream/controller/product/ProductController.java
  src/main/java/com/app/kream/controller/product/ProductControllerSwagger.java
  src/main/java/com/app/kream/controller/scrap/ScrapController.java
  src/main/java/com/app/kream/controller/scrap/ScrapControllerSwagger.java
  src/main/java/com/app/kream/domain/Member.java
  src/main/java/com/app/kream/domain/Product.java
  src/main/java/com/app/kream/domain/Scrap.java
  src/main/java/com/app/kream/exception/ErrorMessage.java
  src/main/java/com/app/kream/exception/SuccessMessage.java
  src/main/java/com/app/kream/exception/model/BusinessException.java
  src/main/java/com/app/kream/repository/MemberRepository.java
  src/main/java/com/app/kream/repository/ProductRepository.java
  src/main/java/com/app/kream/repository/ScrapRepository.java
  src/main/java/com/app/kream/service/MemberService.java
  src/main/java/com/app/kream/service/ProductService.java
  src/main/java/com/app/kream/service/ScrapService.java
  src/main/java/com/app/kream/service/dto/ExampleDto.java
  src/main/resources/application.properties
  src/test/java/com/app/kream/KreamApplicationTests.java
Labels: 🐻‍❄️ 민재, 🔧 Chore

#7 Feat/#6 - 세부 상품 조회 API 구현
  src/main/java/com/app/kream/controller/product/ProductController.java
  src/main/java/com/app/kream/controller/product/ProductControllerSwagger.java
  src/main/java/com/app/kream/domain/Product.java
  src/main/java/com/app/kream/exception/ErrorMessage.java
  src/main/java/com/app/kream/exception/SuccessMessage.java
  src/main/java/com/app/kream/exception/model/NotFoundException.java
  src/main/java/com/app/kream/service/MemberService.java
  src/main/java/com/app/kream/service/ProductService.java
  src/main/java/com/app/kream/service/dto/DetailProductResponse.java
  src/main/java/com/app/kream/service/dto/ExampleDto.java
  src/main/java/com/app/kream/service/dto/StyleResponse.java
Labels: 🐻‍❄️ 민재, ✨ Feat

#8 Feat/#5 Scarp 등록 API 구현
  src/main/java/com/app/kream/controller/scrap/ScrapController.java
  src/main/java/com/app/kream/controller/scrap/ScrapControllerSwagger.java
  src/main/java/com/app/kream/repository/ScrapRepository.java
  src/main/java/com/app/kream/service/ScrapService.java
  src/main/java/com/app/kream/service/dto/ScrapCreateRequest.java
Labels: :tiger: 기훈, ✨ Feat

#12 Feat/#9 - 발매 정보 조회 GET API 구현
  src/main/java/com/app/kream/controller/product/ProductController.java
  src/main/java/com/app/kream/controller/product/ProductControllerSwagger.java
  src/main/java/com/app/kream/domain/Product.java
  src/main/java/com/app/kream/exception/SuccessMessage.java
  src/main/java/com/app/kream/repository/ScrapRepository.java
  src/main/java/com/app/kream/repository/StyleImageRepository.java
  src/main/java/com/app/kream/service/ProductService.java
  src/main/java/com/app/kream/service/ScrapService.java
  src/main/java/com/app/kream/service/StyleImageService.java
  src/main/java/com/app/kream/service/dto/DetailProductResponse.java
  src/main/java/com/app/kream/service/dto/ReleaseProductInfoResponse.java
  src/main/java/com/app/kream/service/dto/ReleaseProductResponse.java
  src/main/java/com/app/kream/service/dto/ScrapCreateRequest.java
Labels: 🐻‍❄️ 민재, ✨ Feat

#14 Feat/#11
  build.gradle
  src/main/java/com/app/kream/config/InitializeDefaultConfig.java
  src/main/java/com/app/kream/config/db.csv
  src/main/java/com/app/kream/domain/Product.java
  src/main/java/com/app/kream/repository/StyleImageRepository.java
  src/main/java/com/app/kream/service/dto/DetailProductResponse.java
Labels: :tiger: 기훈, 🔧 Chore, InitConfig

#15 Feat/#13 - 추천 상품 조회 GET API 구현
  src/main/java/com/app/kream/controller/product/ProductController.java
  src/main/java/com/app/kream/controller/product/ProductControllerSwagger.java
  src/main/java/com/app/kream/exception/SuccessMessage.java
  src/main/java/com/app/kream/service/ProductService.java
  src/main/java/com/app/kream/service/dto/DetailProductResponse.java
  src/main/java/com/app/kream/service/dto/ForYouProductResponse.java
  src/main/java/com/app/kream/service/dto/JustDropProductResponse.java
  src/main/java/com/app/kream/service/dto/RecommendProductResponse.java
Labels: 🐻‍❄️ 민재, ✨ Feat

#16 Feat/#10 - 스크랩 삭제 API 구현
  src/main/java/com/app/kream/controller/scrap/ScrapController.java
  src/main/java/com/app/kream/controller/scrap/ScrapControllerSwagger.java
  src/main/java/com/app/kream/domain/Scrap.java
  src/main/java/com/app/kream/exception/ErrorMessage.java
  src/main/java/com/app/kream/exception/SuccessMessage.java
  src/main/java/com/app/kream/repository/ScrapRepository.java
  src/main/java/com/app/kream/service/ScrapService.java
  src/main/java/com/app/kream/service/dto/ScrapCreateRequest.java
  src/main/java/com/app/kream/service/dto/ScrapDeleteRequest.java
Labels: 🐛 Fix, :tiger: 기훈, ✨ Feat

#18 Feat/#17 상품 검색 API 구현
  src/main/java/com/app/kream/controller/product/ProductController.java
  src/main/java/com/app/kream/controller/product/ProductControllerSwagger.java
  src/main/java/com/app/kream/domain/Product.java
  src/main/java/com/app/kream/exception/SuccessMessage.java
  src/main/java/com/app/kream/repository/ProductRepository.java
  src/main/java/com/app/kream/service/ProductService.java
  src/main/java/com/app/kream/service/dto/RelateRecommendProductResponse.java
  src/main/java/com/app/kream/service/dto/SearchFindProductResponse.java
  src/main/java/com/app/kream/service/dto/SearchProductResponse.java
Labels: :tiger: 기훈, ✨ Feat

#34 [fix] #33 - relateRecommendProductResponses 수정
  src/main/java/com/app/kream/service/dto/RelateRecommendProductResponse.java
Labels: 🐛 Fix, 🐻‍❄️ 민재
